# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            The Abstraction Layer
tagline:          'Thoughts-in-progress.'
description:      'Thoughts-in-progress. <a href="https://twitter.com/trymarkcatch">@trymarkcatch</a>'
url:              https://theabstractionlayer.com
baseurl:          ''
repository:       markmccaigue.github.io/markmccaigue
comments:         true

author:
  name:           'Mark McCaigue'
  url:            https://twitter.com/trymarkcatch

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/markmccaigue/markmccaigue.github.io
